# Generated by Django 4.2.2 on 2023-08-09 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document2text', '0003_alter_document_document'),
        ('api', '0003_alter_summary_options_rename_text_summary_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document2text.document'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
