# Generated by Django 4.2.2 on 2023-08-06 16:48

from django.db import migrations, models
import document2text.models


class Migration(migrations.Migration):

    dependencies = [
        ('document2text', '0002_alter_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[document2text.models.validate_file_type]),
        ),
    ]
